---
title: "Mini HW 05 - Data visualization"
date: "Due: Sep 14 at 10:05am"
author: "Team assignment"
output: 
  html_document: 
    theme: yeti
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Go to [bit.ly/STA112FSVisFall2017](http://bit.ly/STA112FSVisFall2017) and download the class materials.

2. Select one representative of your team to go to the #assignment-links channel on Slack and click on the link for mini-hw-05, and accept the assignment, and create a new team with your team name. Then, have all the other members of your team accept the assignment and join your existing team.

3. Decide which software you will be using to complete the assignment. R is encouraged not but required.

    - If using R:
        + Clone the repo in RStudio using New Project -> From version control -> Git... (you'll be asked for username and password). **TIP**: Edit the name of the repo to include your teamname, so it only says 04-mini-hw-pokemon. This will keep things a bit more organized.
        + In your Rmd file, uncomment the line that loads the dataset you're assigned.
        + Change the name in the YAML to your **team** name (remember, keep it in quotations) and knit the document. Confirm that the output reflects your name. Go to the Git tab on RStudio and observe the diff. Then check the box next to all changed documents, write an informative commit message, commit, and then push (you'll be asked for username and password again). Once changes are successfully pushed, go back to your repo on GitHub, and confirm that the change you made has been committed.
    - If not using R:
        + Use whatever software you like.
        + Save your assignment.
        + Go to your team repo for the project and drag and drop your submission to the repo. This will upload your file.

### Grading

- Check - All required items completed
- No check - Not all required items completed
