---
title: "Final Project - Showcase your inner data scientist"
date: "Due: Dec 7 at 10:05am"
output: 
  html_document: 
    theme: yeti
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

Pick a dataset, any dataset...

...and do something with it. That is your final project in a nutshell. More details below.

## Background

The final project for this class will consist of a statistical analysis on a dataset of your 
own choosing. The dataset may already exist, or you may collect your own data using a survey 
or by conducting an experiment. If possible, choose a dataset which you are interested in and 
may be useful for another class project or your research if you are working in a lab. The goal 
of this project is for you to demonstrate proficiency in the techniques we have covered in this 
class and apply them to a novel dataset in a meaningful way.

## Data

In order for you to have the greatest chance of success with this project it is important that 
you choose a manageable dataset. This means that the data should be readily accessible and large 
enough that multiple relationships can be explored. As such, your dataset must have at least 50 
observations and between 10 to 20 variables (exceptions can be made but you must speak with me 
first). The dataset’s variables should include categorical variables, discrete numerical 
variables, and continuous numerical variables.

All analyses must be done in RStudio. If you are using a dataset that comes in a format that 
we haven't encountered in class, make sure that you are able to load it into RStudio as this 
can be tricky depending on the source. If you are having trouble ask for help before it is too late.

*Reusing datasets from class:* Do not reuse datasets used in examples / homework in the
class.

## Components

### Project proposal

This is basically your HW 04, so see instructions there.

### Project - Due December 8, at 5pm

After providing the description of your dataset and research question in the 
introduction you must apply what you have learned about descriptive statistics, 
visualizations, correlation and regression, and inference (hypothesis testing 
and confidence intervals) to your dataset. The goal is not to do an exhaustive 
data analysis i.e., do not calculate every statistic and procedure you have 
learned for every variable, but rather let me know that you are proficient at 
using R, and that you are proficient at interpreting and presenting the results. 
Focus on methods that help you begin to answer your research questions. You do 
not have to apply every statistical procedure we learned, but you must apply some.
Also pay attention to your presentation. Neatness, coherency, and clarity will count.

### Presentation - due December 7, in class

10 minutes maximum, and each team member should say something substantial.

You can use any software you like for your final presentation, including R Markdown
to create your slides. There isn't a limit to how many slides you can use, just a 
time limit (10 minutes total). Each team member should get a chance to speak during 
the presentation. Your presentation should not just be an account of everything you 
tried ("then we did this, then we did this, etc."), instead it should convey what 
choices you made, and why, and what you found.

### Delivarables

Your submission should include

* RMarkdown file (formated to clearly present all of your code and results) 
* HTML file
* md file (viewable on GitHub, with all figures)
* Dataset (in csv or RData format)
* Presentation (if using Google Slides, export to PDF and put in repo)

Style and format does count for this assignment, so please take the time to make 
sure everything looks good and your data and code are properly formated.

## Tips

- You're working in the same repo as your teammates now, so merge conflics will happen, issues will arise, and that’s fine! Commit and push often, and ask questions when stuck.

- Review the grading guidelines below and ask questions if any of the expectations are unclear.

- Make sure each team member is contributing, both in terms of quality and quantity of contribution (we will be reviewing commits from different team members).

- Set aside time to work together and apart (physically).

- When you're done, review the .md document on GitHub to make sure you're happy with the final state of your work. Then go get some rest!

## Further details

### Visualizations

The project is very open ended. You should create some kind of compelling 
visualization(s) of this data in R. There is no limit on what tools or 
packages you may use, but sticking to packages we learned in class (`tidyverse`).
You do not need to visualize all of the data at once. A single high quality 
visualization will receive a much higher grade than a large number of poor quality 
visualizations.

### Write up

Your write up must also include a one to two page conclusion and discussion. 
This will require a summary of what you have learned about your research 
question along with statistical arguments supporting your conclusions. Also 
critique your own methods and provide suggestions for improving your analysis. 
Issues pertaining to the reliability and validity of your data, and 
appropriateness of the statistical analysis should be discussed here. A 
paragraph on what you would do differently if you were able to start over 
with the project or what you would do next if you were going to continue 
work on the project should also be included.

### Code:

In your write up your code should be hidden (`echo = FALSE`) so that your 
document is neat and easy to read. However your document should include 
all your code such that if I re-knit your Rmd file I should be 
able to obtain the results you presented.

**Exception:** If you want to highlight something specific about a piece 
of code, you're welcomed to show that portion. 

### Teamwork:

You are to complete the assignment as a team. All team members are expected 
to contribute equally to the completion of this assignment and group 
assessments will be given at its completion - anyone judged to not have sufficient 
contributed to the final product will have their grade penalized. While different 
teams members may have different backgrounds and abilities, it is the responsibility 
of every team member to understand how and why all code and approaches in 
the assignment works.


## Grading

Total                          | 100 pts
-------------------------------|--------
Presentation                   | 35 pts
Write up                       | 40 pts
Classmates' scores             | 5 pts
Team peer evaluaiton           | 10 pts
Repo and document organization | 10 pts

**Team peer evaluation:** You will be asked to fill out a survey where you 
rate the contribution and teamwork of each team member out of 10 points. You will 
additionally report a contribution percentage for each team member. Filling out the 
survey is a prerequisite for getting credit on the team member evaluation.
If you are suggesting that an individual did less than 20% of the work, please
provide some explanation. If any individual gets an average peer score 
indicating that they did less than 10% of the work, this person will receive 
half the grade of the rest of the group.

Grading of the project will take into account the following:

- Content - What is the quality of research and/or policy question and relevancy 
of data to thosequestions?
- Correctness - Are statistical procedures carried out and explained correctly?
- Writing and Presentation - What is the quality of the statistical presentation, 
writing, and explanations?
- Creativity and Critical Thought - Is the project carefully thought out? Are the 
limitations carefully considered? Does it appear that time and effort went into 
the planning and implementation of the project?

A general breakdown of scoring is as follows:

- 90%-100% - Outstanding effort. Student understands how to apply all statistical 
concepts, can put the results into a cogent argument, can identify weaknesses in 
the argument, and can clearly communicate the results to others.
- 80%-89% - Good effort. Student understands most of the concepts, puts together 
an adequate argument, identifies some weaknesses of their argument, and communicates 
most results clearly to others.
- 70%-79% - Passing effort. Student has misunderstanding of concepts in several 
areas, has some trouble putting results together in a cogent argument, and communication 
of results is sometimes unclear.
- 60%-69% - Struggling effort. Student is making some effort, but has misunderstanding 
of many concepts and is unable to put together a cogent argument. Communication 
of results is unclear.
- Below 60% - Student is not making a sufficient effort.

**Late penalty:**

- Late, but within 24 hours of due date/time: -20%
- Any later: no credit 