---
title: "HW 02 - Modeling course evaluations"
date: "Due: Oct 24 at 10:05am"
output: 
  html_document: 
    theme: yeti
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Many college courses conclude by giving students the opportunity to evaluate the course and the instructor anonymously. However, the use of these student evaluations as an indicator of course quality and teaching effectiveness is often criticized because these measures may reflect the influence of non-teaching related characteristics, such as the physical appearance of the instructor. The article titled, ``Beauty in the classroom: instructors’ pulchritude and putative pedagogical productivity" (Hamermesh and Parker, 2005) found that instructors who are viewed to be better looking receive higher instructional ratings. (Daniel S. Hamermesh, Amy Parker, Beauty in the classroom: instructors pulchritude and putative pedagogical productivity, Economics of Education Review, Volume 24, Issue 4, August 2005, Pages 369-376, ISSN 0272-7757, 10.1016/j.econedurev.2004.07.013. http://www.sciencedirect.com/science/article/pii/S0272775704001165.)

For this assignmenrt you will analyze the data from this study in order to learn what goes into a positive professor evaluation.

The data were gathered from end of semester student evaluations for a large sample of professors from the University of Texas at Austin. In addition, six students rated the professors’ physical appearance. (This is aslightly modified version of the original data set that was released as part of the replication data for Data Analysis Using Regression and Multilevel/Hierarchical Models (Gelman and Hill, 2007).) The result is a data frame where each row contains a different course and columns represent variables about the courses and professors.

## Codebook

1. `score` - Average professor evaluation score: (1) very unsatisfactory - (5) excellent
1. `rank` - Rank of professor: teaching, tenure track, tenure
1. `ethnicity` - Ethnicity of professor: not minority, minority
1. `gender` - Gender of professor: female, male
1. `language` - Language of school where professor received education: english or non-english
1. `age` - Age of professor
1. `cls_perc_eval` - Percent of students in class who completed evaluation
1. `cls_did_eval` - Number of students in class who completed evaluation
1. `cls_students` - Total number of students in class
1. `cls_level` - Class level: lower, upper
1. `cls_profs` - Number of professors teaching sections in course in sample: single, multiple
1. `cls_credits` - Number of credits of class: one credit (lab, PE, etc.), multi credit
1. `bty_f1lower` - Beauty rating of professor from lower level female: (1) lowest - (10) highest
1. `bty_f1upper` - Beauty rating of professor from upper level female: (1) lowest - (10) highest
1. `bty_f2upper` - Beauty rating of professor from upper level female: (1) lowest - (10) highest
1. `bty_m1lower` - Beauty rating of professor from lower level male: (1) lowest - (10) highest
1. `bty_m1upper` - Beauty rating of professor from upper level male: (1) lowest - (10) highest
1. `bty_m2upper` - Beauty rating of professor from upper level male: (1) lowest - (10) highest


## Part 1: Data Manipulation 

1.  Create a new variable called `bty_avg` that is the average attractiveness
    score of the six students for each professor (`bty_f1lower` through `bty_m2upper`). 
    (Hint: Do this in one pipe, and use the `rowwise` function. See function help for 
    more info.)

## Part 2: Exploratory Data Analysis

2.  Describe the distribution of `score`. Is the distribution skewed? What does 
    that tell you about how students rate courses? Is this what you expected to 
    see? Why, or why not? Include any summary statistics and visualizations
    you use in your response.

3.  Select a numerical variable other than `score` and visualize and describe
    the relationship between these two variables.

## Part 3: Simple linear regression

4.  Replot the scatterplot from Question 3, but this time use  
    `geom_point(position = "jitter")`? What does "jitter" mean? What was misleading about the initial scatterplot?

5.  Let's see if the apparent trend in the plot is something more than
    natural variation. Fit a linear model called `m_bty` to predict average
    professor evaluation `score` by average beauty rating (`bty_avg`) and add 
    the regression line to your plot. Write out the equation for the linear 
    model and interpret the slope.

## Part 4: Multiple linear regression

6.  Fit a new linear model called `m_bty_gen` to predict average
    professor evaluation `score` based on average beauty rating (`bty_avg`) and
    `gender`. How does the adusted $R^2$ of this model and the previous one
    compare? Has the addition of `gender` to the model changed the parameter
    estimate (slope) for `bty_avg`?

7.  What is the equation of the line corresponding to *just* male professors?
    
8.  For two professors who received the same beauty rating, which gender tends 
    to have the higher course evaluation score?
    
9. How does the relationship between beauty and evaluation score
    vary between male and female professors?
    
10.  Create a new model called `m_bty_rank` with `gender` removed and `rank` 
    added in. How is R handling a categorical variables that has more 
    than two levels? Note that the rank variable has three levels: `teaching`, 
    `tenure track`, `tenured`.

## Part 5: The search for the best model

11. Which variable would you expect to be the worst predictor of 
    evaluation scores? Why? *Hint:* Think about which variable would you 
    expect to not have any association with the professor's score.

12. Check your suspicions from the previous exercise. Include the model output
    in your response.

13. Interpret the coefficient associated with the ethnicity variable in context.

14. Drop the variable that results in the highest gain of adjusted R-squared.
    Did the coefficients change?
    (One of the things that makes multiple regression interesting is that
    coefficient estimates depend on the other variables that are included in
    the model.) If not, what does this say about whether or not the dropped
    variable was collinear with the other explanatory variables?

15. Using backward-selection with adjusted R-squared as the selection 
    criterion, determine the *best* model. You do not need to show all 
    steps in your answer, just the output for the final model. Also, 
    write out the linear model for predicting score based on the final 
    model you settle on.

16. Based on your final model, describe the characteristics of a professor and 
    course at University of Texas at Austin that would be associated with a high
    evaluation score.

17. Would you be comfortable generalizing your conclusions to apply to professors
    generally (at any university)? Why or why not?


### Tips

- You're working in the same repo as your teammates now, so merge conflics will happen, issues will arise, and that’s fine! Commit and push often, and ask questions when stuck.

- Review the grading guidelines below and ask questions if any of the expectations are unclear.

- Make sure each team member is contributing, both in terms of quality and quantity of contribution (we will be reviewing commits from different team members).

- Set aside time to work together and apart (physically).

- When you're done, review the .md document on GitHub to make sure you're happy with the final state of your work. Then go get some rest!

### Grading

Total                                                   | 100 pts
--------------------------------------------------------|--------
Part 1: Data manipulation                               | 5 pts
Part 2: EDA                                             | 20 pts
Part 3: SLR                                             | 15 pts
Part 4: MLR                                             | 20 pts
Part 5: Search for best model                           | 25 pts
Code quality                                            | 5 pts
Document organization  (team name, code chunk names, commtis, overall organization, etc.)                                     | 10 pt
